name: CI
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - master
defaults:
  run:
    shell: bash

jobs:
  filter:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.event.head_commit.author.username == 'jph00') || github.event_name != 'push'
    steps:
      - run: |
          echo "passed filter"
          echo "event_name: ${{ github.event_name }}"
          echo "head_commit.author.username: ${{ github.event.head_commit.author.username }}"

  fastcore:
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu, windows, macos]
        py:  [3.6, 3.7, 3.8]
        include:
          - os: windows
            shell: "/usr/bin/bash"
          - os: ubuntu 
            shell: "/bin/bash"
          - os: macos 
            shell: "/bin/bash"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        pip install -Uqq nbdev
        pip install -e ".[dev]"
    - name: Check if notebooks are synced and cleaned
      uses: fastai/workflows/nb@master
    - name: Run tests
      run: nbdev_test_nbs
      env:
        SHELL:  ${{ matrix.shell }}

  nbdev-integration-test:
    needs: filter
    container: fastai/jekyll
    runs-on: ubuntu-latest
    steps:
    - name: clone this branch [fastcore]
      uses: actions/checkout@v2
      with:
        path: fastcore_lib
    - name: clone nbdev
      uses: actions/checkout@v2
      with:
        repository: 'fastai/nbdev'
        path: nbdev   
    - name: Install libraries
      run: |
        cd fastcore_lib && pip install -Ue .[dev]
        cd ../nbdev && pip install -Ue .[dev]
    - name: test nbdev notebooks
      run: |
        cd nbdev && make test
        
  fastai-integration-test:
    needs: filter
    container: fastai/fastai
    runs-on: ubuntu-latest
    env:
      download: "true"
    strategy:
      matrix:
        nb: ['[0-1]', '[2-3]', '[4-5]','[6-7]', '[8-9]']
    steps:
    - name: clone this branch [fastcore]
      uses: actions/checkout@v2
      with:
        path: fastcore/
        
    - name: clone fastai
      uses: actions/checkout@v2
      with:
        repository: 'fastai/fastai'
        path: fastai
        
    - name: Install libraries
      run: |
        pip install -Uqq nbdev
        cd fastai && pip install -Ue .[dev]
        cd ../fastcore && pip install -Ue .[dev]

    - name: check for cache hit
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.fastai/data
        key: 'fastai-test-data-v4'

    - name: download data
      if: env.download == 'true' && steps.cache.outputs.cache-hit != 'true'
      run: |
        ipython /root/download_testdata.py
        mkdir -p $HOME/.fastai/data
        find $HOME/.fastai/archive/ -name "*.tgz" -exec tar -xzvf {} -C $HOME/.fastai/data \;
          
    - name: Test fastai notebooks
      run: |
        cd fastai
        nbdev_test_nbs --flags '' --n_workers 3 --pause 1.0 --fname "nbs/[0-9]${{matrix.nb}}*.ipynb"
